CC = cc
CFLAGS = -O0
objects = foo.o main.o
headers = foo.h
output = foo

$(output): $(objects)
	$(CC) -o $@ $?

.SUFFIXES: .c .o
.c.o:
	$(CC) -c $(CFLAGS) -o $@ $<

clean:
	rm -f $(output) $(objects)
