CC = cc
CFLAGS = -O0
objects = foo.o main.o
targets = foo

all: $(targets)

$(targets): $(objects)
	$(CC) -o $@ $(objects)

foo.o: foo.c
	$(CC) -c $(CFLAGS) -o $@ $<

main.o: main.c foo.h
	$(CC) -c $(CFLAGS) -o $@ $<

clean:
	rm -f $(targets) $(objects)
